services:
  - type: web
    name: london-bikes-dashboard
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync
    startCommand: uv run gunicorn app:server --bind 0.0.0.0:$PORT
